use sakila;

delimiter $
create procedure INSERIR_FILM_ESTOQUE(IN CODIGO_STORE INT, IN ULTIMO_NUMERO_MATRICULA INT)
BEGIN
	DECLARE DONE BOOL DEFAULT FALSE;
    DECLARE VAR_FILME INT;
    
    DECLARE CURSOR_FILME_FORA_ESTOQUE CURSOR FOR
		SELECT 
			FILM_ID
		FROM
			FILM LEFT JOIN INVENTORY USING (FILM_ID)
        WHERE 
			INVENTORY_ID IS NULL
		AND INVENTORY.FILM_ID = CODIGO_FILME;
        
	DECLARE CONTINUE HANDLER FOR
		NOT FOUND SET DONE = TRUE;
	
    OPEN CURSOR_FILME_FORA_ESTOQUE;
    
    PROCESS_LISTA: LOOP
    FETCH CURSOR_FILME_FORA_ESTOQUE INTO VAR_FILME;
    SET CONTADOR = 1;
    
    REPEAT
    
     INSERT INTO INVENTORY(INVENTORY_ID, STORE_ID, FILM_ID)
		VALUES(DEFAULT, CODIGO_STORE, VAR_FILME);
    
    UNTIL CONTADOR = ULTIMO_NUMERO_MATRICULA
    END REPEAT;
    
    END LOOP;
	
END$
DELIMITER ;